package Vistas.ABM;

import Clases.Add_modify_user.Rank;
import Conexion.Conexiones;
import Vistas.Menu_window;
import java.sql.Connection;
import java.sql.SQLException;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

public class New_user_window extends javax.swing.JFrame {

    private final char caracterEchoPredeterminado;
    private final char caracterEchoPredeterminado2;
    Connection con = Conexiones.Conexion();
    static int flag, rankId = 0, userId = 0, estado = 0, color = 0;
    ImageIcon icondark, icondark2;

    public New_user_window() {
        initComponents();
        this.setLocationRelativeTo(null);
        caracterEchoPredeterminado = password_text.getEchoChar();
        caracterEchoPredeterminado2 = repeat_password_text.getEchoChar();
        Clases.Add_modify_user.ShowCombosNewUser(con, rank_user);
        rank_user.setEnabled(false);
        rank_user.setSelectedIndex(1);

        String textoLargo = "<html>¡No hay usuarios! Complete todos los campos para registrar un nuevo usuario ¡Recuerde no olvidarse de nada!</html>";
        lbl_information.setText(textoLargo);

        color = Clases.General_configurations.Color();
        if (color == 1) {
            icondark = new ImageIcon(getClass().getResource("/Recursos/view_passdark2.png"));
            icondark2 = new ImageIcon(getClass().getResource("/Recursos/view_passdark.png"));
            view_pass_button.setIcon(icondark2);
            view_rpass_button.setIcon(icondark2);
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        background_panel = new javax.swing.JPanel();
        lbl_information = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        username_text = new javax.swing.JTextField();
        password_text = new javax.swing.JPasswordField();
        repeat_password_text = new javax.swing.JPasswordField();
        view_pass_button = new javax.swing.JButton();
        view_rpass_button = new javax.swing.JButton();
        email_text = new javax.swing.JTextField();
        rank_user = new javax.swing.JComboBox<>();
        jSeparator2 = new javax.swing.JSeparator();
        back_button = new javax.swing.JButton();
        save_button = new javax.swing.JButton();
        dni_text = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);

        background_panel.setBackground(new java.awt.Color(255, 255, 255));
        background_panel.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 102), 3, true), "Nuevo usuario", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 24))); // NOI18N

        lbl_information.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        username_text.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        username_text.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Nombre de usuario:", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 18))); // NOI18N
        username_text.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                username_textKeyTyped(evt);
            }
        });

        password_text.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        password_text.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Contraseña:", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 18))); // NOI18N
        password_text.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                password_textKeyTyped(evt);
            }
        });

        repeat_password_text.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        repeat_password_text.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Repetir contraseña:", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 18))); // NOI18N

        view_pass_button.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/view_pass.png"))); // NOI18N
        view_pass_button.setBorderPainted(false);
        view_pass_button.setContentAreaFilled(false);
        view_pass_button.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        view_pass_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                view_pass_buttonActionPerformed(evt);
            }
        });

        view_rpass_button.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/view_pass.png"))); // NOI18N
        view_rpass_button.setBorderPainted(false);
        view_rpass_button.setContentAreaFilled(false);
        view_rpass_button.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        view_rpass_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                view_rpass_buttonActionPerformed(evt);
            }
        });

        email_text.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        email_text.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Correo Electronico:", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 18))); // NOI18N
        email_text.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                email_textKeyTyped(evt);
            }
        });

        rank_user.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        rank_user.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Rango:", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 18))); // NOI18N
        rank_user.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        rank_user.setFocusable(false);
        rank_user.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rank_userActionPerformed(evt);
            }
        });

        back_button.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/back_button.png"))); // NOI18N
        back_button.setBorderPainted(false);
        back_button.setContentAreaFilled(false);
        back_button.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        back_button.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/back_button_ro.png"))); // NOI18N
        back_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                back_buttonActionPerformed(evt);
            }
        });

        save_button.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/save_button.png"))); // NOI18N
        save_button.setBorderPainted(false);
        save_button.setContentAreaFilled(false);
        save_button.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        save_button.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/save_button_ro.png"))); // NOI18N
        save_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                save_buttonActionPerformed(evt);
            }
        });

        dni_text.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        dni_text.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Documento:", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 18))); // NOI18N
        dni_text.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                dni_textKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout background_panelLayout = new javax.swing.GroupLayout(background_panel);
        background_panel.setLayout(background_panelLayout);
        background_panelLayout.setHorizontalGroup(
            background_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(background_panelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(background_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(email_text)
                    .addComponent(lbl_information, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jSeparator1)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, background_panelLayout.createSequentialGroup()
                        .addGroup(background_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(password_text, javax.swing.GroupLayout.PREFERRED_SIZE, 409, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(repeat_password_text, javax.swing.GroupLayout.PREFERRED_SIZE, 409, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 58, Short.MAX_VALUE)
                        .addGroup(background_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(view_rpass_button, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                            .addComponent(view_pass_button, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jSeparator2)
                    .addGroup(background_panelLayout.createSequentialGroup()
                        .addComponent(username_text, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(dni_text, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(background_panelLayout.createSequentialGroup()
                        .addComponent(rank_user, javax.swing.GroupLayout.PREFERRED_SIZE, 366, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(background_panelLayout.createSequentialGroup()
                        .addComponent(back_button, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(save_button, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        background_panelLayout.setVerticalGroup(
            background_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(background_panelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbl_information, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(background_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(username_text, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dni_text, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(background_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(view_pass_button, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(password_text))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(background_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(repeat_password_text, javax.swing.GroupLayout.DEFAULT_SIZE, 61, Short.MAX_VALUE)
                    .addComponent(view_rpass_button, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(email_text, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rank_user, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(background_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(save_button, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(back_button, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(background_panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(background_panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void back_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_back_buttonActionPerformed
        this.dispose();
    }//GEN-LAST:event_back_buttonActionPerformed

    private void view_pass_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_view_pass_buttonActionPerformed
        if (color == 0) {
            ImageIcon icon1 = new ImageIcon(getClass().getResource("/Recursos/view_pass2.png"));
            ImageIcon icon2 = new ImageIcon(getClass().getResource("/Recursos/view_pass.png"));
            char caracterActual = password_text.getEchoChar();
            if (caracterActual != (char) 0) {
                password_text.setEchoChar((char) 0);
                view_pass_button.setIcon(icon1);
            } else {
                password_text.setEchoChar(caracterEchoPredeterminado);
                view_pass_button.setIcon(icon2);
            }
        } else if (color == 1) {
            char caracterActual = password_text.getEchoChar();
            if (caracterActual != (char) 0) {
                password_text.setEchoChar((char) 0);
                view_pass_button.setIcon(icondark);
            } else {
                password_text.setEchoChar(caracterEchoPredeterminado);
                view_pass_button.setIcon(icondark2);
            }
        }
    }//GEN-LAST:event_view_pass_buttonActionPerformed

    private void view_rpass_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_view_rpass_buttonActionPerformed
        if (color == 0) {
            ImageIcon icon1 = new ImageIcon(getClass().getResource("/Recursos/view_pass2.png"));
            ImageIcon icon2 = new ImageIcon(getClass().getResource("/Recursos/view_pass.png"));
            char caracterActual = repeat_password_text.getEchoChar();
            if (caracterActual != (char) 0) {
                repeat_password_text.setEchoChar((char) 0);
                view_rpass_button.setIcon(icon1);
            } else {
                repeat_password_text.setEchoChar(caracterEchoPredeterminado2);
                view_rpass_button.setIcon(icon2);
            }
        } else if (color == 1) {
            char caracterActual = repeat_password_text.getEchoChar();
            if (caracterActual != (char) 0) {
                repeat_password_text.setEchoChar((char) 0);
                view_rpass_button.setIcon(icondark);
            } else {
                repeat_password_text.setEchoChar(caracterEchoPredeterminado2);
                view_rpass_button.setIcon(icondark2);
            }
        }
    }//GEN-LAST:event_view_rpass_buttonActionPerformed

    private void save_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_save_buttonActionPerformed
        String nomb = username_text.getText();
        String ps = password_text.getText();
        String rps = repeat_password_text.getText();
        String em = email_text.getText();
        String dni = dni_text.getText();
        if (!nomb.trim().isEmpty() && !ps.trim().isEmpty() && !rps.trim().isEmpty() && !em.trim().isEmpty() && rankId != 0 && !dni.trim().isEmpty()) {
            if (em.contains("@") && em.contains(".")) {
                if (ps.equals(rps)) {
                    try {
                        int cerrar = Clases.Add_modify_user.AddNewUser(con, nomb, ps, rps, em, 1, flag, userId, estado, dni);
                        if (cerrar == 1) {
                            new Menu_window().setVisible(true);
                            this.dispose();
                        }
                    } catch (SQLException e) {
                        JOptionPane.showMessageDialog(null, "ERROR AL REGISTRAR: " + e);
                    }
                } else {
                    JOptionPane.showMessageDialog(null, "Las contraseñas no coinciden!");
                }
            } else {
                JOptionPane.showMessageDialog(null, "Introduzca un correo valido!");
            }

        } else {
            JOptionPane.showMessageDialog(null, "¡HAY CAMPOS VACIOS! Por favor, revise");
        }
    }//GEN-LAST:event_save_buttonActionPerformed

    private void rank_userActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rank_userActionPerformed
        Object value = rank_user.getSelectedItem();
        if (value instanceof Rank) {
            Rank r = (Rank) value;
            rankId = r.getId();
        }
    }//GEN-LAST:event_rank_userActionPerformed

    private void dni_textKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_dni_textKeyTyped
        char r = evt.getKeyChar();
        if (Character.isISOControl(r)) {
            return; // permite borrar, mover, etc.
        }
        if (!Character.isDigit(r)) {
            getToolkit().beep();
            evt.consume();
        }
        if (dni_text.getText().length() >= 9) {
            evt.consume();
        }
    }//GEN-LAST:event_dni_textKeyTyped

    private void username_textKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_username_textKeyTyped
        if (username_text.getText().length() >= 44) {
            evt.consume();
        }
    }//GEN-LAST:event_username_textKeyTyped

    private void password_textKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_password_textKeyTyped
        if (password_text.getText().length() >= 44) {
            evt.consume();
        }
    }//GEN-LAST:event_password_textKeyTyped

    private void email_textKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_email_textKeyTyped
        if (email_text.getText().length() >= 44) {
            evt.consume();
        }
    }//GEN-LAST:event_email_textKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(New_user_window.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(New_user_window.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(New_user_window.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(New_user_window.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new New_user_window().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton back_button;
    private javax.swing.JPanel background_panel;
    private javax.swing.JTextField dni_text;
    private javax.swing.JTextField email_text;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JLabel lbl_information;
    private javax.swing.JPasswordField password_text;
    private javax.swing.JComboBox<Rank> rank_user;
    private javax.swing.JPasswordField repeat_password_text;
    private javax.swing.JButton save_button;
    private javax.swing.JTextField username_text;
    private javax.swing.JButton view_pass_button;
    private javax.swing.JButton view_rpass_button;
    // End of variables declaration//GEN-END:variables
}
